spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3333/ecommerce
    username: root
    password: root
  flyway:
    enabled: true
    locations: classpath:db/migration  # Folder where Flyway looks for SQL migrations
    baseline-on-migrate: true          # Baselines the database if it isn't empty
    baseline-version: 1 
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  sql:
    init:
      mode: never
  application:
    name: user

Build:
  version: 1.2
